_wandb:
    value:
        cli_version: 0.23.1
        e:
            zpropcy7pchxi7pxkm1ngwjj6c92qord:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1021821579264"
                        used: "763672297472"
                email: eashwar.sathyamurthy@gmail.com
                executable: C:\Users\eashw\AppData\Local\Programs\Python\Python39\python.exe
                git:
                    commit: bcc765ecab1f7d7fa92bdc9721d90e26eb143d58
                    remote: https://github.com/Eashwar-S/Routing_agent.git
                gpu: NVIDIA GeForce RTX 3080 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Laptop GPU
                      uuid: GPU-c3625721-4190-b411-5053-4ba1cad4d876
                host: Eashwar
                memory:
                    total: "34048368640"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\eashw\Desktop\post_graduation_plan\Collaborations\Routing_agent\src\train.py
                python: CPython 3.9.0
                root: C:\Users\eashw\Desktop\post_graduation_plan\Collaborations\Routing_agent
                startedAt: "2026-01-08T19:44:31.436577Z"
                writerId: zpropcy7pchxi7pxkm1ngwjj6c92qord
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
            "4": 3.9.0
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
device:
    value: cuda
embedding_dim:
    value: 128
learning_rate:
    value: 0.01
num_epochs:
    value: 200
num_nodes:
    value: 50
train_batches_per_epoch:
    value: 100
